# Generated by Django 3.1 on 2020-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_group', models.CharField(max_length=500)),
                ('room_type', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Residencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('host_id', models.FloatField()),
                ('host_name', models.CharField(max_length=500)),
                ('neighbourhood', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('minimum_nights', models.FloatField()),
                ('number_of_reviews', models.FloatField()),
                ('last_review', models.DateTimeField()),
                ('reviews_per_month', models.FloatField()),
                ('calculated_host_listings_count', models.FloatField()),
                ('availability_365', models.FloatField()),
                ('neighbourhood_group', models.CharField(max_length=500)),
            ],
        ),
    ]
