# Generated by Django 3.1 on 2020-08-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviajem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='aviajem.residencias')),
            ],
        ),
    ]
